<?php

namespace Tests;

use PHPUnit\Framework\TestCase;
use Zeroplex\Sftp\Sftp;

class SshFtpTest extends TestCase
{
    protected $sftp;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function tearDown(): void
    {
        $this->sftp = null;
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testForNothing()
    {
        $this->assertTrue(true);
    }
}